const cfg=window.CALIP_CONFIG||{}; const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY); const $=id=>document.getElementById(id);
let products=[],stocks=[],counts=[],selectedProduct=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pick=(o,...ks)=>{for(const k of ks)if(o?.[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];return ''};
function msg(t,ok=false){$('inventoryMsg').textContent=t;$('inventoryMsg').style.color=ok?'#17633f':'#a12d35'}
async function init(){try{const p=await sb.from('productos').select('*');if(p.error)throw p.error;products=p.data||[];const s=await sb.from('lotes_stock').select('*');if(s.error)throw s.error;stocks=s.data||[];await loadCounts();$('status').textContent=`✓ ${products.length} productos conectados`;}catch(e){$('status').textContent='Error de conexión';msg('No se pudo conectar: '+e.message)}}
function search(){const q=$('invSearch').value.trim().toLowerCase();if(!q){$('results').innerHTML='';return}const rows=products.filter(p=>JSON.stringify(p).toLowerCase().includes(q)).slice(0,12);$('results').innerHTML=rows.map((p,i)=>`<button class="result" data-i="${i}">${esc(pick(p,'codigo','cod','id'))} — ${esc(pick(p,'descripcion','nombre','desc_material'))}</button>`).join('');rows.forEach((p,i)=>$('results').children[i].onclick=()=>select(p));}
function select(p){selectedProduct=p;$('results').innerHTML='';$('invSearch').value=pick(p,'codigo','cod','id');$('selectedProduct').innerHTML=`<strong>${esc(pick(p,'codigo','cod','id'))}</strong> — ${esc(pick(p,'descripcion','nombre','desc_material'))}<br><small>${esc(pick(p,'linea','línea'))}</small>`;}
async function save(){if(!selectedProduct)return msg('Selecciona un producto.');const qty=$('invQty').value;if(qty==='')return msg('Ingresa la cantidad.');if(!$('invVencimiento').value)return msg('Ingresa el vencimiento.');const row={id:String(pick(selectedProduct,'codigo','cod','id'))+'_'+Date.now(),codigo:String(pick(selectedProduct,'codigo','cod','id')),descripcion:String(pick(selectedProduct,'descripcion','nombre','desc_material')),linea:String(pick(selectedProduct,'linea','línea')),cantidad:Number(qty),cajas:Number($('invCajas').value||0),unidades:Number($('invUnidades').value||0),vencimiento:$('invVencimiento').value,fecha:new Date().toISOString().slice(0,10),usuario:'CALIP'};msg('Guardando...',true);const {error}=await sb.from('lotes_conteo').insert(row);if(error)return msg('No se pudo guardar: '+error.message);msg('✓ Conteo guardado en Supabase.',true);$('invQty').value='';$('invCajas').value=0;$('invUnidades').value=0;$('invVencimiento').value='';await loadCounts();}
async function loadCounts(){const {data,error}=await sb.from('lotes_conteo').select('*').order('created_at',{ascending:false}).limit(500);if(error)return msg('Error leyendo conteos: '+error.message);counts=data||[];render();}
function render(){$('inventoryBody').innerHTML=counts.map(x=>{const stock=stocks.filter(s=>String(s.codigo||'')===String(x.codigo||'')).reduce((a,s)=>a+Number(s.cantidad||0),0);const c=Number(x.cantidad||0);return `<tr><td>${esc(x.codigo)}</td><td>${esc(x.descripcion)}</td><td>${esc(x.linea)}</td><td>${esc(x.vencimiento)}</td><td>${stock}</td><td>${c}</td><td>${c-stock}</td><td>${esc(x.cajas)}</td><td>${esc(x.unidades)}</td><td>${esc(x.fecha)}</td></tr>`}).join('')}
$('invSearch').addEventListener('input',search);$('saveCount').addEventListener('click',save);$('reload').addEventListener('click',loadCounts);init();
